[package]
name = "bft"
version = "0.1.0"
authors = ["Rg <daimaldd@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
runtime-fmt = "*"
exonum_sodiumoxide = "0.0.16"
bigint = "*"
hex = "*"
sha3 = "0.7.3"
util_rs = {git = "https://github.com/laohanlinux/util-rs.git"}